---
build_from:
  aarch64: ghcr.io/hassio-addons/base:12.2.2
  amd64: ghcr.io/hassio-addons/base:12.2.2
  armhf: ghcr.io/hassio-addons/base:12.2.2
  armv7: ghcr.io/hassio-addons/base:12.2.2
  i386: ghcr.io/hassio-addons/base:12.2.2
codenotary:
  base_image: ma@bite-de-cheval.com
  signer: ma@bite-de-cheval.com
