---
name: FreeBox
version: dev
slug: freebox
description: Controls your freebox
url: https://github.com/matguig/addon-freebox
codenotary: ma@bite-de-cheval.com
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
